%\VignetteIndexEntry{Sample Guitar workflow}
%\VignetteKeywords{Guitar,visualization,sequencing,RNA methylation,m6A, m5C}
%\VignettePackage{Guitar}
\documentclass[]{article}

\usepackage{times}
\usepackage{hyperref}

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}
\newcommand{\Rcode}[1]{{\texttt{#1}}}

\newcommand{\software}[1]{\textsf{#1}}
\newcommand{\R}{\software{R}}
\newcommand{\exomePeak}{\Rpackage{exomePeak}}
\newcommand{\bam}{\texttt{BAM}}


\title{An Introduction to \Rpackage{Guitar} Package}
\author{Lin Zhang, PhD}
\date{Modified: 26 September, 2017. Compiled: \today}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

<<options,echo=FALSE>>=
options(width=60)
@ 


\section{Quick Start with Guitar}
This is a manual for Guitar2 package. The Guitar2 package is aimed for RNA landmark-guided transcriptomic analysis of RNA-reated genomic features. 

The Guitar2 package enables the comparison of multiple genomic features, which need to be stored in a name list. Please see the following example, which reads 1000 RNA m6A methylation sites into R for detection. Of course, in actual data analysis, features may come from multiple sets of resources.
<<Genomic Features>>=
library(Guitar2)
# genomic features imported into named list
stBedFiles <- list(system.file("extdata", "m6A_mm10_exomePeak_1000peaks_bed12.bed", 
                                package="Guitar2"))
@ 

With the following script, we may generate the transcriptomic distribution of genomic features to be tested, and the result will be automatically saved into a PDF file under the working directory with prefix ``example''. With the \Rfunction{Guitar2Plot} function, the gene annotation can be downloaded from internet automatically with a genome assembly number provided; however, this feature requires working internet and might take a longer time. The toy Guitar coordinates generated internally should never be re-used in other real data analysis.
<<label=rep_dendro_1_plot,eval=FALSE>>=
count <- Guitar2Plot(txGenomeVer = "mm10",
                     stBedFiles = stBedFiles,
                     miscOutFilePrefix = NA)

@


In a more efficent protocol, in order to re-use the gene annotation and \Rclass{Guitar2 coordinates}, you will have to build Guitar Coordiantes from a \Rclass{txdb} object in a separate step. The transcriptDb contains the gene annotation information and can be obtained in a number of ways, .e.g,  download the complete gene annotation of species from UCSC automatically, which might takes a few minutes. In the following analysis, we load the \Rclass{Txdb} object from a toy dataset provided with the Guitar package. Please note that this is only a very small part of the complete hg19 transcriptome, and the \Rclass{Txdb} object provided with \Rpackage{Guitar2} package should not be used in real data analysis. With a \Rclass{TxDb} object that contains gene annotation information, we in the next build \Rclass{Guitar2 coordiantes}, which is essentially a bridge connects the transcriptomic landmarks and genomic coordinates.
<<Guitar2 coordiantes>>=
txdb_file <- system.file("extdata", "mm10_toy.sqlite", 
                         package="Guitar2")                       
txdb <- loadDb(txdb_file)
guitarTxdb <- makeGuitarTxdb(txdb = txdb)
# Or use gff. file to generate guitarTxdb
# Or use getTxdb() to download TxDb from internet:
# txdb <- getTxdb(txGenomeVer="hg19")
# guitarTxdb <- makeGuitarTxdb(txdb)


@

You may now generate the Guitar plot from the named list of genome-based features.
<<label=Guitarcoordiantes, fig=TRUE,echo=TRUE,height=6,width=12>>=
Guitar2Plot(txTxdb =  txdb,
            stBedFiles = stBedFiles,
            miscOutFilePrefix = "example2")

@
Alternatively, you may also optionally include the promoter DNA region and tail DNA region on the 5' and 3' side of a transcript in the plot with parameter \Rcode{headOrtail =TRUE}.
<<label=withDNA2, fig=TRUE,echo=TRUE,height=6,width=12,eval=FALSE>>=
Guitar2Plot(txTxdb = txdb, 
            stBedFiles = stBedFiles,
            headOrtail = TRUE)
@

Alternatively, you may also optionally include the Confidence Interval for guitar2 plot with parameter \Rcode{enableCI = TRUE}. 
<<label=withDNA3,fig=TRUE,echo=TRUE,height=6,width=12>>=
Guitar2Plot(txTxdb = txdb, 
            stBedFiles = stBedFiles,
            headOrtail = TRUE,
            enableCI = TRUE)
@

\section{Supported Data Format}
Besides BED file, \Rpackage{Guitar2} package also supports  GRangesList and GRanges  data structures. Please see the following examples.

<<label=mm10_example,fig=TRUE,echo=TRUE,height=6,width=12>>=
# import different data formats into a named list object.
# These genomic features are using mm10 genome assembly
stBedFiles <- list(system.file("extdata", "H3K4me3_mm10_1000peaks.bed", package="Guitar2"),
                   system.file("extdata", "m6A_mm10_exomePeak_1000peaks_bed12.bed", package="Guitar2"),
                   system.file("extdata", "m6A_mm10_exomePeak_1000peaks_bed6.bed", package="Guitar2"))
# Build Guitar Coordinates
txdb_file <- system.file("extdata", "mm10_toy.sqlite", 
                         package="Guitar2")
txdb <- loadDb(txdb_file)


# Guitar Plot
Guitar2Plot(txTxdb = txdb, 
            stBedFiles = stBedFiles,
            headOrtail = TRUE,
            enableCI = TRUE,
            stGroupName = c("BED3","BED12","BED6"))
@

\section{Processing of sampling sites information} 

We can select parameters for site sampling.

<<label=sample,fig=TRUE,echo=TRUE,height=6,width=12>>=
stGRangeLists = vector("list", length(stBedFiles))
sitesPoints <- list()
 for (i in seq_len(length(stBedFiles))) {
      stGRangeLists[[i]] <-  blocks(import(stBedFiles[[i]]))
    }
    for (i in seq_len(length(stGRangeLists))) {
      sitesPoints[[i]] <- samplePoints(stGRangeLists[i], 
                                  stSampleNum = 10,
                                  stAmblguity = 5,
                                  pltTxType =  c("mrna"), 
                                  stSampleModle = "Equidistance", 
                                  mapFilterTranscript = TRUE,
                                  guitarTxdb = guitarTxdb)
    }
@

@


\section{Guitar2 Coordinates - Transcriptomic Landmarks Projected on Genome} 
The \Robject{guitarTxdb} object contains the genome-projected transcriptome coordinates, which can be valuable for evaluating transcriptomic information related applications, such as checking the quality of MeRIP-Seq data. The \Robject{Guitar2 coordinates} are essentially the genomic projection of standardized transcript-based coordiantes, making a viable bridge beween the landmarks on transcript and genome-based coordinates. 

It is based on the \Rclass{txdb} object input, extracts the transcript information in txdb, selects the transcripts that match the parameters according to the component parameters set by the user, and saves according to the transcript type (tx, mrna, ncrna).

<<label=session,eval=TRUE>>=
guitarTxdb <- makeGuitarTxdb(txdb = txdb,
                             txAmblguity = 5,
                             txTxComponentProp = c(0.15, 0.7, 0.15),
                             txMrnaComponentProp = c(0.1, 0.1, 0.6, 0.05, 0.15),
                             txLncrnaComponentProp = c(0.2,0.6,0.2),
                             pltTxType = c("tx","mrna","ncrna"),
                             txPrimaryOnly = TRUE)
@

\section{Check the Overlapping between Different Components} 

We can also check the distribution of the Guitar coordinates built. 

<<label=lcp3,fig=TRUE,echo=TRUE,height=6,width=12>>=
gcl <- list(guitarTxdb$tx$tx)
Guitar2Plot(txTxdb  = txdb,
                stGRangeLists = gcl,
                stSampleNum = 500,
                enableCI = TRUE,
                pltTxType =  c("tx","mrna","ncrna")
                )
@

Alternatively, we can extract the RNA components, check the distribution of tx components in the transcriptome

<<label=comp,eval=TRUE>>=
  GuitarCoords <- guitarTxdb$tx$txComponentGRange
  type <- paste(mcols(GuitarCoords)$componentType,mcols(GuitarCoords)$txType)
  key <- unique(type)
  landmark <- list(1,2,3,4,5,6,7,8,9,10,11)
  names(landmark) <- key  
  for (i in 1:length(key)) {
  landmark[[i]] <- GuitarCoords[type==key[i]]
}
Guitar2Plot(txTxdb  = txdb ,
                stGRangeLists = landmark[1:3],
                pltTxType =  c("tx")
)

@
Check the distribution of mRNA components in the transcriptome
Guitar2Plot(txTxdb  = txdb ,
                stGRangeLists = landmark[4:8],
                pltTxType =  c("mrna")
)

@

Check the distribution of lncRNA components in the transcriptome
Guitar2Plot(txTxdb  = txdb ,
                stGRangeLists = landmark[9:11],
                pltTxType =  c("ncrna")
)


@


\section{Session Information} 
<<label=session,eval=TRUE>>=
sessionInfo()
@

\end{document}
